name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '明文源吗'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Install Obfuscator
        run: npm install javascript-obfuscator

      - name: Obfuscate from local source file
        run: node obfuscate.js

      - name: Update UUID in Obfuscated Script
        run: node update_uuid.js
        env:
          CFNEW_UUID: ${{ vars.CFNEW_UUID }}

      - name: Create wrangler.toml
        run: node create_wrangler_toml.js
        env:
          CF_ACCOUNT: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
